### ISSUE TITLE
buildsystemdata fails with latest static data export

### ISSUE THREAD

**Issue by nyrocron** [marbindrakon/eve-wspace#174]
Running on Debian 8.1 (Jessie), Python 2.7.9, MariaDB (10.0.16-MariaDB-1 (Debian)) in a VM.

On a new install (pulled from 69e64d1c8d28d5237256116db8a3c4622c691e95), after the `syncdb` and `migrate --fake` steps, `./manage.py buildsystemdata` fails with the latests static data export from https://www.fuzzwork.co.uk/dump/mysql56-carnyx-1.0-113321.tbz2 with the following error:

    (eve-wspace)maptool@jessie-vm:~/eve-wspace/evewspace$ ./manage.py buildsystemdata
    Beginning System Table Construction
    First Pass Complete, beginning lowsec pass
    Traceback (most recent call last):
      File "./manage.py", line 10, in <module>
        execute_from_command_line(sys.argv)
      File "/home/maptool/eve-wspace/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
        utility.execute()
      File "/home/maptool/eve-wspace/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/home/maptool/eve-wspace/local/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
        self.execute(*args, **options.__dict__)
      File "/home/maptool/eve-wspace/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
        output = self.handle(*args, **options)
      File "/home/maptool/eve-wspace/local/lib/python2.7/site-packages/django/core/management/base.py", line 415, in handle
        return self.handle_noargs(**options)
      File "/home/maptool/eve-wspace/evewspace/core/management/commands/buildsystemdata.py", line 64, in handle_noargs
        lowsec = KSystem.objects.get(name=system.name)
      File "/home/maptool/eve-wspace/local/lib/python2.7/site-packages/django/db/models/manager.py", line 151, in get
        return self.get_queryset().get(*args, **kwargs)
      File "/home/maptool/eve-wspace/local/lib/python2.7/site-packages/django/db/models/query.py", line 310, in get
        self.model._meta.object_name)
    Map.models.DoesNotExist: KSystem matching query does not exist.

With the Mosaic SDE (https://www.fuzzwork.co.uk/dump/mysql56-mosaic-1.0-112241.tbz2) it works without problems.

**Comment by Zumochi** [comment]
Having the same issue with a new install. FreeBSD 10.1, Python 2.7.9.

Works with the latest Mosaic dump (1.2).

**Comment by Ulyssys** [comment]
Just here to confirm the issue on my own install. I ended up using the Mosaic 1.2 dump and it worked fine.

**Comment by craigcalef** [comment]
I also had this problem.  These seem to be from the 5 new shattered wormholes with Carnyx.

Able to work around by changing line 68 of core/management/commands/buildsystemdata.py from:

"except LocationWormholeClass.DoesNotExist:"  to  "except:"

**Comment by marbindrakon** [comment]
This has been fixed in develop.
